spring: 
    profiles: 
        active: 
        - dev

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/ 
  instance:
    instance-id: provider-8001   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: I am a provider demo
  company.name: www.jd.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management: 
    security: 
        enabled: false

myName: zhangsan
---
server: 
    port: 8001
spring: 
    profiles: dev
    application:
        name: provider
    rabbitmq:
        host: 10.0.56.57
        port: 5672
        username: guest
        password: guest
---
server: 
    port: 8009
spring: 
    profiles: test
    application:
        name: provider
    rabbitmq:
        host: 10.0.56.57
        port: 5672
        username: guest
        password: guest
      

